name: wallpaper
description: "A dynamic wallpaper application."
pulish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  video_player: ^2.8.2
  cached_network_image: ^3.3.1
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  permission_handler: ^11.2.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/videos/
    - assets/thumbnails/
