// Mocks generated by Mockito 5.4.6 from annotations
// in flutterwin/test/services/logics/player_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter/foundation.dart' as _i2;
import 'package:flutterwin/services/logics.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeValueNotifier_0<T> extends _i1.SmartFake
    implements _i2.ValueNotifier<T> {
  _FakeValueNotifier_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PlayerLogic].
///
/// See the documentation for Mockito's code generation for more information.
class MockPlayerLogic extends _i1.Mock implements _i3.PlayerLogic {
  @override
  _i2.ValueNotifier<String> get playingWallpaperIdNotifier =>
      (super.noSuchMethod(
            Invocation.getter(#playingWallpaperIdNotifier),
            returnValue: _FakeValueNotifier_0<String>(
              this,
              Invocation.getter(#playingWallpaperIdNotifier),
            ),
            returnValueForMissingStub: _FakeValueNotifier_0<String>(
              this,
              Invocation.getter(#playingWallpaperIdNotifier),
            ),
          )
          as _i2.ValueNotifier<String>);

  @override
  void add(String? wallpaperId) => super.noSuchMethod(
    Invocation.method(#add, [wallpaperId]),
    returnValueForMissingStub: null,
  );

  @override
  void setAutoPlayOrder(_i3.AutoPlayOrder? order) => super.noSuchMethod(
    Invocation.method(#setAutoPlayOrder, [order]),
    returnValueForMissingStub: null,
  );

  @override
  void setAutoPlayInterval(Duration? interval) => super.noSuchMethod(
    Invocation.method(#setAutoPlayInterval, [interval]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> startAutoPlay() =>
      (super.noSuchMethod(
            Invocation.method(#startAutoPlay, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void stopAutoPlay() => super.noSuchMethod(
    Invocation.method(#stopAutoPlay, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> play(String? wallpaperId) =>
      (super.noSuchMethod(
            Invocation.method(#play, [wallpaperId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> pause(String? wallpaperId) =>
      (super.noSuchMethod(
            Invocation.method(#pause, [wallpaperId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  bool isPlaying(String? wallpaperId) =>
      (super.noSuchMethod(
            Invocation.method(#isPlaying, [wallpaperId]),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);
}
